name = "lean-projects"
defaultTargets = ["ProjectiveGeometry", "GraphTheory"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0-rc1"

[[lean_lib]]
name = "ProjectiveGeometry"

[[lean_lib]]
name = "GraphTheory"
