/-
Copyright (c) 2025 Bhavik Mehta. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Bhavik Mehta, Kevin Buzzard
-/
-- Jakub : worked-out exercise sheets from Bhavik Mehta's course
-- https://github.com/b-mehta/formalising-mathematics-notes/tree/main/FormalisingMathematics2026/Section19graphTheory
-- (tweaked to compile with current mathlib)
import Mathlib.Combinatorics.SimpleGraph.Acyclic
import Mathlib.Combinatorics.SimpleGraph.Operations

section Sheet1
/-

# Graph theory

This sheet is just an overview of the basic API for graphs; there are
no sorrys.

So, how do graphs work in Lean? Actually it took a long time
to come up with a definition people were happy with. One issue
is that different people mean different things by "graph". In this
section we're going to stick to "simple graphs", which means
that you have a type of vertices `V`, and edges go between two
distinct vertices in `V`. The rules for a simple graph:

1) Edges are undirected (so they don't have a source and a target, they
just have two ends, which are vertices)
2) You can't have more than one edge between two distinct vertices.
3) You can't have an edge going from a vertex to itself.

Because of rule 2, you can represent an edge as a yes/no question:
"is there an edge between `v` and `w` or not?". In other words
you can represent edges as a function `adj : V → V → Prop`, and you
don't need a separate set or type `E` for edges. `adj` is short
for "adjacent", so `adj v w` means "there's an edge between `v` and `w`,
i.e. "`v` is adjacent to `w`".

Rule 1 means that `adj` is symmetric (if `v` is adjacent to `w` then
`w` is adjacent to `v`), and rule 3 means that it is irreflexive,
i.e. `∀ v, ¬ adj v v`.

Here's how to say "let `G` be a (simple) graph with vertex set `V`"

-/
variable (V : Type) (G : SimpleGraph V)

-- Here's how to say two edges are adjacent
example (v w : V) : Prop :=
  G.Adj v w

-- If v is adjacent to w then w is adjacent to v
example (v w : V) : G.Adj v w → G.Adj w v :=
  G.adj_symm

-- v isn't adjacent to itself
example (v : V) : ¬G.Adj v v :=
  G.irrefl

/-

Longish interlude: here's one way to make a square graph. It's quite laborious.
Lean is better at proving theorems than making explicit examples!

v1 -- v2
|     |
|     |
v3 -- v4
-/
section SquareGraph

-- the vertex set of the square graph; we make it a type with four terms
inductive SQV : Type
  | v1 : SQV
  | v2 : SQV
  | v3 : SQV
  | v4 : SQV

open SQV

-- so I can write `v1` not `sqV.v1`
-- here's one boring way of making the edges -- an inductive proposition
inductive SQE : SQV → SQV → Prop
  | e12 : SQE v1 v2
  | e21 : SQE v2 v1
  | e24 : SQE v2 v4
  | e42 : SQE v4 v2
  | e34 : SQE v3 v4
  | e43 : SQE v4 v3
  | e13 : SQE v1 v3
  | e31 : SQE v3 v1

-- Now let's make the graph
def SQG : SimpleGraph SQV where
  Adj := SQE
  symm := by
    constructor
    -- do all the cases for the two vertices and the edge
    rintro (_ | _ | _ | _) (_ | _ | _ | _) (_ | _ | _ | _ | _ | _ | _ | _)
    -- now 8 goals; find the right constructor for sqE in all cases
    repeat constructor
  loopless := ⟨by rintro (_ | _ | _ | _) (_ | _ | _ | _ | _ | _ | _ | _)⟩

end SquareGraph

-- Here's how to make a triangle graph; it's rather easier
-- Here `Fin 3` is the "canonical" type with 3 terms; to give a term of type `Fin 3`
-- is to give a pair consisting of a natural `n` and a proof that `n < 3`.
-- Here the `complete_graph` function is doing all the work for you.
example : SimpleGraph (Fin 3) :=
  SimpleGraph.completeGraph (Fin 3)

-- The collection of all simple graphs on a fixed vertex set `V` form a Boolean algebra
-- (whatever that is)
example : BooleanAlgebra (SimpleGraph V) := by infer_instance

-- and in particular they form a lattice, so you can do stuff like this:
example : SimpleGraph V :=
  ⊥
-- empty graph

example : SimpleGraph V :=
  ⊤
-- complete graph

example (G H : SimpleGraph V) : SimpleGraph V :=
  G ⊔ H
-- union of vertices
-- etc etc, and you can even do this

example (G : SimpleGraph V) : SimpleGraph V := Gᶜ
-- complement, i.e. an edge exists in `Gᶜ` between
-- distinct vertices `v` and `w` iff it doesn't
-- exist in `G`
-- The *support* of a graph is the vertices that have an edge coming from them.
example (v : V) : v ∈ G.support ↔ ∃ w, G.Adj v w := by rfl
-- true by definition

-- The `neighborSet` of a vertex is all the vertices connected to it by an edge.
example (v : V) : Set V :=
  G.neighborSet v

example (v w : V) : w ∈ G.neighborSet v ↔ G.Adj v w :=
  Iff.rfl
-- true by defn

-- The type `Sym2 V` is the type of unordered pairs of elements of `V`, i.e. `V × V`
-- modulo the equivalence relation generated by `(v,w)~(w,v)`.
-- So you can regard the edges as a subset of `sym2 V`, and that's `G.edge_set`
example (G : SimpleGraph V) : Set (Sym2 V) :=
  SimpleGraph.edgeSetEmbedding _ G

-- You can use `v ∈ e` notation if `e : Sym2 v`
-- For example, `G.incidence_set v` is the set of edges coming out of `v`,
-- regarded as elements of `Sym2 V`
example (v : V) :
    G.incidenceSet v = {e ∈ SimpleGraph.edgeSetEmbedding _ G | v ∈ e} :=
  rfl

-- You can delete a set of edges from `G` using `G.delete_edges`
example (E : Set (Sym2 V)) : SimpleGraph V :=
  G.deleteEdges E
-- if E contains edges not in G then this doesn't matter, they're just ignored.

-- You can push a graph forward along an injection
example (W : Type) (f : V ↪ W) : SimpleGraph W :=
  G.map f

-- and pull it back along an arbitrary map
example (U : Type) (g : U → V) : SimpleGraph U :=
  G.comap g

-- The degree of a vertex is the size of its neighborSet.
-- Better assume some finiteness conditions to make this work.
variable [G.LocallyFinite]

-- now we have `Finset` versions of some `set` things. For example
example (v : V) : G.degree v = Finset.card (G.neighborFinset v) :=
  rfl

-- If `H` is another graph on a vertex set `W`
variable (W : Type) (H : SimpleGraph W)

-- then we can consider types of various maps between graphs
example : Type :=
  G →g H
-- maps f:V → W such that v₁~v₂ -> f(v₁)~f(v₂)

example : Type :=
  G ↪g H
-- injections f : V → W such that v₁~v₂ ↔ f(v₁)~f(v₂)

example : Type :=
  G ≃g H
-- isomorphisms of graphs
end Sheet1

section Sheet2
/-

Cut and pasted directly from the module docstring from the file imported above:

# Graph connectivity

In a simple graph,

* A *walk* is a finite sequence of adjacent vertices, and can be
  thought of equally well as a sequence of directed edges.

* A *trail* is a walk whose edges each appear no more than once.

* A *path* is a trail whose vertices appear no more than once.

* A *cycle* is a nonempty trail whose first and last vertices are the
  same and whose vertices except for the first appear no more than once.

(and then there's a warning that in topology some of these words are
used to mean different things)

So of course the question is how to actually do this in Lean. Here's how.
Let `G` be a simple graph with vertex set `V`, and say `v, w, x` in `V`

-/

variable (V : Type) (G : SimpleGraph V) (v w x : V)

-- The type of all walks from `v` to `w`
example : Type :=
  G.Walk v w

-- The empty walk from `v` to `v`
example : G.Walk v v :=
  SimpleGraph.Walk.nil

-- oh that's a bit annoying, let's open `SimpleGraph`
open SimpleGraph

example : G.Walk v v :=
  Walk.nil

-- Add an edge to the beginning of a walk
example (h : G.Adj v w) (a : G.Walk w x) : G.Walk v x :=
  Walk.cons' v w x h a

-- There's also walk.cons where you don't have to specify the vertices
example (h : G.Adj v w) (a : G.Walk w x) : G.Walk v x :=
  Walk.cons h a

-- concatenation of walks
example (a : G.Walk v w) (b : G.Walk w x) : G.Walk v x :=
  a.append b

-- Let `a` be a walk from `v` to `w`
variable (a : G.Walk v w)

-- length of `a` is a natural
example : ℕ :=
  a.length

-- reverse of `a`
example : G.Walk w v :=
  a.reverse

-- n'th vertex visited in `a`
example (n : ℕ) : V :=
  a.getVert n

-- 0'th vertex is where we start
example : a.getVert 0 = v :=
  Walk.getVert_zero a

-- (Walk length)'th vertex is where we end.
example : a.getVert a.length = w :=
  Walk.getVert_length a

-- Support of `a` is the list of vertices it goes through
example : List V :=
  a.support

-- Edges of `a` is the list of edges it goes through
example : List (Sym2 V) :=
  a.edges

-- A walk is a *trail* if it has no repeating edges.
example : Prop :=
  a.IsTrail

-- A walk is a *path* if it has no repeating vertices.
example : Prop :=
  a.IsPath

-- Paths are sufficiently common that `G.path v w` is defined to be the
-- subtype `{p : G.walk v w // p.is_path}`. So to give a term of type `G.path v w`
-- is to give a pair consisting of a walk `p : G.walk v w` and a proof of `p.IsPath`.
-- A walk is a *circuit* at `v : V` if it's a nonempty trail beginning and ending at `v`.
example (b : G.Walk v v) : Prop :=
  b.IsCircuit

-- A walk is a *cycle* at `v : V` if it's a circuit at `v` whose only repeating vertex
-- is `v` (which appears exactly twice).
example (b : G.Walk v v) : Prop :=
  b.IsCycle

-- Exercise : give an example of a circuit which isn't a cycle. Can you do it in Lean?
abbrev H := SimpleGraph.completeGraph (Fin 5)

def Counterex : H.Walk 0 0 :=
  Walk.nil
    |> Walk.cons ((top_adj 1 0).2 (by lia))
    |> Walk.cons ((top_adj 2 1).2 (by lia))
    |> Walk.cons ((top_adj 0 2).2 (by lia))
    |> Walk.cons ((top_adj 3 0).2 (by lia))
    |> Walk.cons ((top_adj 4 3).2 (by lia))
    |> Walk.cons ((top_adj 0 4).2 (by lia))

example : Counterex.IsCircuit ∧ ¬ Counterex.IsCycle :=
  ⟨{edges_nodup := by decide
    ne_nil := by intro h; injection h},
  by
    intro h
    have : ¬ Counterex.support.tail.Nodup := by decide
    exact this h.support_nodup⟩

-- Remark: a Lean solution is in the solutions.
-- Example theorem in the API: given a walk `p` from `v` to `u` and an edge from `u` to `v`,
-- putting them together gives a cycle iff `p` is a path and the edge from `u` to `v`
-- is not in the edges of `p`.
example {u v : V} (p : G.Walk v u) (h : G.Adj u v) :
    (Walk.cons h p).IsCycle ↔ p.IsPath ∧ s(u, v) ∉ p.edges :=
  Walk.cons_isCycle_iff p h

-- Given a walk from `v` to `w` and a vertex `u` in the support of the walk,
-- truncate the walk so it starts at `v` and finishes at `u`.
open scoped Classical

noncomputable section

-- don't ask me
example (a : G.Walk v w) (u : V) (hu : u ∈ a.support) : G.Walk v u :=
  a.takeUntil u hu

-- With the same hypotheses, return the rest of the walk from `u` to `w`
example (a : G.Walk v w) (u : V) (hu : u ∈ a.support) : G.Walk u w :=
  a.dropUntil u hu

-- Example in the API : those two walks added together give the original
-- walk again
example (a : G.Walk v w) (u : V) (hu : u ∈ a.support) :
    (a.takeUntil u hu).append (a.dropUntil u hu) = a :=
  Walk.take_spec a hu

-- Two vertices `u` and `v` satisfy `G.reachable u v : Prop` if there's a walk from `u` to `v`.
example : G.Reachable v w ↔ Nonempty (G.Walk v w) :=
  Iff.rfl

def join {u v w : V} : G.Walk u v → G.Walk v w → G.Walk u w
  | Walk.nil, b => b
  | Walk.cons h a, b => Walk.cons h (join a b)

def reverse {u v : V} : G.Walk u v → G.Walk v u
  | Walk.nil => Walk.nil
  | Walk.cons h a => join V G (reverse a) (Walk.cons h.symm Walk.nil)

-- true by definition
-- Can you show that `G.reachable` is an equivalence relation?
example : Equivalence G.Reachable :=
  {refl := by
    intro v
    exact ⟨Walk.nil⟩
   symm := by
    intro u v huv
    have ⟨a⟩ := huv
    exact ⟨reverse V G a⟩
   trans := by
    intro u v w huv hvw
    have ⟨a⟩ := huv
    have ⟨b⟩ := hvw
    exact ⟨join V G a b⟩}

-- A graph is "preconnected" if `G.reachable v w` is true for any `v w : V`.
-- Note that this includes the empty graph with `V` empty, for silly logic reasons.
example : G.Preconnected ↔ ∀ v w : V, G.Reachable v w :=
  Iff.rfl
-- true by definition

-- A graph is connected iff it's preconnected and nonempty.
example : G.Connected ↔ G.Preconnected ∧ Nonempty V :=
  connected_iff G

end
end Sheet2

section Sheet3
/-

# Trees and forests

A *forest* is a graph with no cycles. A *tree* is a connected forest.

Here's how to do this in Lean. Let `G` be a graph with vertex set `V`.

-/

open SimpleGraph
variable (V : Type) (G : SimpleGraph V)

-- Here's how to say "G is a forest"
example : Prop :=
  G.IsAcyclic

-- It's defined to mean "For all `v : V`, every walk from `v` to `v` is not a cycle. "
example : G.IsAcyclic ↔ ∀ (v : V) (p : G.Walk v v), ¬p.IsCycle := by rfl

-- Here's how to say "G is a tree"
example : Prop :=
  G.IsTree

example : G.IsTree ↔ G.Connected ∧ G.IsAcyclic :=
  G.isTree_iff

-- Here are some harder theorems from the library. Recall that a *path* is a walk
-- with no repeated vertices.
-- A graph is acyclic iff for all `v w : V`, there's at most one path from `v` to `w`.
example : G.IsAcyclic ↔ ∀ (v w : V) (p q : G.Path v w), p = q :=
  SimpleGraph.isAcyclic_iff_path_unique

-- A graph is a tree iff `V` is nonempty and for all `v w : V`,
-- there's exactly one path from `v` to `w`.
example : G.IsTree ↔ Nonempty V ∧ ∀ v w : V, ∃! p : G.Walk v w, p.IsPath :=
  SimpleGraph.isTree_iff_existsUnique_path

-- If you want a logic puzzle, rephrase this in terms of `G.path`
-- (i.e. use the theorem above and then unpack and repack the RHS)
example : G.IsTree ↔ Nonempty V ∧ ∀ v w : V, ∃! _ : G.Path v w, True := by
  rw [SimpleGraph.isTree_iff_existsUnique_path]
  constructor
  · intro ⟨n, h⟩; use n
    intro v w
    obtain ⟨p, hp, hun⟩ := h v w
    use ⟨p, hp⟩, (True.intro)
    intro q _
    ext
    exact hun q.val q.property
  · intro ⟨n, h⟩; use n
    intro v w
    have ⟨p, _, hun⟩ := h v w
    use p.val, p.property
    intro q hq
    rw [show q = (⟨q, hq⟩ : G.Path v w).val from rfl]
    rw [hun ⟨q, hq⟩ (True.intro)]

-- Here's a result which isn't yet in mathlib: `G` is a tree iff it's a maximal acyclic graph
-- If you fill this one in, let me know and we can put it in mathlib!
-- Jakub : it has since been added to mathlib, but here is my attempt
example : G.IsTree ↔ Nonempty V ∧ Maximal SimpleGraph.IsAcyclic G := by
  constructor
  · intro hG
    use hG.connected.nonempty, hG.isAcyclic
    intro H hH hGH u v huvH
    by_contra huvG
    obtain ⟨p, hp⟩ := hG.connected.exists_isPath v u
    let p' := p.mapLe hGH
    let c := p'.cons huvH
    apply hH c
    rw [c.isCycle_iff_isPath_tail_and_le_length]
    constructor
    · rw [Walk.tail_cons]
      exact (p'.isPath_copy _ _).mpr (Walk.IsPath.mapLe _ hp)
    · rw [Walk.length_cons, Nat.succ_le_succ_iff]
      rw [show p'.length = p.length from Walk.length_map _ p]
      match hl : p.length with
      | 0 =>
        exfalso; apply huvH.ne.symm
        exact Walk.eq_of_length_eq_zero hl
      | 1 =>
        exfalso; apply huvG; symm
        exact Walk.adj_of_length_eq_one hl
      | n + 2 => exact Nat.le_add_left 2 n
  · rintro ⟨hn, hG⟩
    refine ⟨?_, hG.prop⟩; constructor
    intro u v
    let H := G ⊔ (edge u v)
    by_contra hreach
    have huv_ne : u ≠ v := by intro he; apply hreach; rw [he]
    have huv_nadj : ¬ G.Adj u v := by intro ha; exact hreach ha.reachable
    have hH : ¬ H.IsAcyclic := by
      intro hH
      have hGH : G < H := G.lt_sup_edge u v huv_ne huv_nadj
      apply not_le_of_gt hGH
      exact hG.right hH (le_of_lt hGH)
    unfold IsAcyclic at hH; push Not at hH
    obtain ⟨w, c, hc⟩ := hH
    have huvH : H.Adj u v := by
      rw [sup_adj]; right
      rw [edge_adj]; refine ⟨?_, huv_ne⟩; left
      tauto
    have hG_eq : H \ (edge u v) = G := by
      rwa [sup_sdiff, sdiff_self, sup_bot_eq, sdiff_edge]
    have hbr : H.IsBridge s(u, v) := by
      rw [isBridge_iff]
      unfold deleteEdges
      rwa [← edge, hG_eq]
    rw [isBridge_iff_forall_cycle_notMem huvH] at hbr
    have huvG := hbr c hc
    have h : ∀ e ∈ c.edges, e ∈ G.edgeSet := by
      intro e he
      have heH := Walk.edges_subset_edgeSet c he
      rw [edgeSet_sup] at heH
      cases heH with
      | inl heG => exact heG
      | inr he_uv =>
        exfalso
        rw [edgeSet_edge_of_ne huv_ne] at he_uv
        apply Set.eq_of_mem_singleton at he_uv
        rw [he_uv] at he
        contradiction
    let c' := c.transfer G h
    have hc' := hc.transfer h
    exact hG.prop c' hc'

end Sheet3
